[[plugins]]
  package = "@netlify/plugin-nextjs"

[build]
  command = "pnpm prisma generate && pnpm build"

[build.environment]
  NODE_VERSION = "24"

[functions]
  included_files = ["dev.db"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache"
