"use client"; import { formatDate } from "@/lib/utils"; import { amountInWords } from "@/lib/calculations";
import type { QH } from "./quotation-header-form"; import type { LineItem } from "@/hooks/use-quotation";
export function QuotationPreview({ header, lineItems, totals }: { header: QH; lineItems: LineItem[]; totals: { subTotal: number; cgst: number; sgst: number; roundOff: number; netAmount: number; totalGst: number } }) {
  return <div className="border rounded-md bg-white text-black p-4 font-sans text-xs shadow-sm h-full overflow-auto">
    <div className="text-center mb-3"><h2 className="text-sm font-bold">SALINI TRADERS</h2><p className="text-xs font-bold">Pala - Thodupuzha Road, Kanattupura, Pala, Kottayam</p><p className="text-[10px]">Ph: +91 9539066366, Mob: +91 9539088488</p><p className="text-[11px] font-bold">GSTIN: 32AESFS0236G1Z3</p></div>
    <div className="text-center font-bold text-xs border border-black py-1 mb-2">Quotation</div>
    <table className="w-full mb-2 text-[11px]"><tbody><tr><td className="w-1/2 align-top"><strong>{header.customerName || "(Name)"}</strong>{header.customerAddress && <><br/>Address: {header.customerAddress}</>}{header.customerPlace && <><br/>Place: {header.customerPlace}</>}{header.customerGstin && <><br/>GSTIN: {header.customerGstin}</>}</td><td className="w-1/2 align-top"><strong>Quot. No</strong>: {header.refNo || "-"}<br/><strong>Date</strong>: {header.quotDate ? formatDate(new Date(header.quotDate)) : ""}<br/><strong>Ref. No</strong>: {header.refNo}</td></tr></tbody></table>
    <table className="w-full border-collapse border border-black text-[10px] mb-2"><thead><tr className="bg-gray-100"><th className="border border-black p-1 text-center w-6">#</th><th className="border border-black p-1 text-left">Description</th><th className="border border-black p-1 text-center w-10">GST</th><th className="border border-black p-1 text-center w-20">Qty/Uom</th><th className="border border-black p-1 text-center w-20">Weight</th><th className="border border-black p-1 text-right w-16">Rate</th><th className="border border-black p-1 text-right w-20">Net Value</th></tr></thead><tbody>{lineItems.map((item, i) => <tr key={item.key}><td className="border border-black p-1 text-center">{i+1}</td><td className="border border-black p-1">{item.description}</td><td className="border border-black p-1 text-center">{item.gstPercent}%</td><td className="border border-black p-1 text-center">{item.qty > 0 ? `${item.qty} ${item.unit}` : "-"}</td><td className="border border-black p-1 text-center">{item.weightKg != null ? `${item.weightKg} Kg` : "-"}</td><td className="border border-black p-1 text-right">{item.rate.toFixed(2)}</td><td className="border border-black p-1 text-right">{item.netValue.toFixed(2)}</td></tr>)}
    <tr><td colSpan={5} className="border border-black p-1 text-right font-bold">Sub Total:</td><td className="border border-black p-1 text-right">{totals.subTotal.toFixed(2)}</td></tr><tr><td colSpan={5} className="border border-black p-1 text-right font-bold">CGST:</td><td className="border border-black p-1 text-right">{totals.cgst.toFixed(2)}</td></tr><tr><td colSpan={5} className="border border-black p-1 text-right font-bold">SGST:</td><td className="border border-black p-1 text-right">{totals.sgst.toFixed(2)}</td></tr><tr><td colSpan={5} className="border border-black p-1 text-right font-bold">Round Off:</td><td className="border border-black p-1 text-right">{totals.roundOff.toFixed(2)}</td></tr><tr><td colSpan={5} className="border border-black p-1 text-right font-bold">Net Amount</td><td className="border border-black p-1 text-right font-bold">{totals.netAmount.toFixed(2)}</td></tr></tbody></table>
    <div className="flex justify-between text-[10px] mb-2"><span>E&amp;OE</span><span className="font-bold">{amountInWords(totals.netAmount)}</span></div>
    <div className="text-[10px]"><div className="text-right mb-2"><p className="font-bold">For SALINI TRADERS</p><p>Authorized Signatory</p></div><p className="font-bold">LOADING CHARGE AND TRANSPORTATION CHARGES EXTRA</p><div className="flex justify-between mt-1"><span>Delivery: {header.deliveryTerms}</span><span>Validity: {header.validity}</span></div><div className="flex justify-between"><span>GST: {header.gstNote}</span><span>Payment: {header.paymentTerms}</span></div><p className="mt-1 text-[9px]">Certified that the particulars given above are true and correct.</p><p className="font-bold text-[9px]">Bank: SBI, SME Pala - A/C: 42459778328 - IFSC: SBIN0063661</p></div>
  </div>;
}
