"use client"; import { useState, useEffect } from "react"; import { use } from "react";
import { QuotationLineItems } from "@/components/quotations/quotation-line-items"; import { QuotationTotals } from "@/components/quotations/quotation-totals";
import { QuotationPreview } from "@/components/quotations/quotation-preview"; import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { FileDown, Pencil, Copy, ArrowLeft, Loader2 } from "lucide-react";
import Link from "next/link"; import { useRouter } from "next/navigation"; import { computeTotals } from "@/lib/calculations"; import { toast } from "sonner";
export default function ViewQuotationPage({ params }: { params: Promise<{ id: string }> }) { const { id } = use(params); const router = useRouter();
  const [q, setQ] = useState<Record<string, unknown> | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetch(`/api/quotations/${id}`).then(r => r.json()).then(d => { setQ(d); setLoading(false); }); }, [id]);
  async function duplicate() { const r = await fetch(`/api/quotations/${id}/duplicate`, { method:"POST" }); if (r.ok) { const d = await r.json(); toast.success("Duplicated"); router.push(`/quotations/${d.id}/edit`); } }
  if (loading) return <div className="flex items-center justify-center h-64"><Loader2 className="h-8 w-8 animate-spin text-muted-foreground"/></div>;
  if (!q) return <div className="text-center py-12">Not found.</div>;
  const lineItems = ((q.lineItems as Array<Record<string, unknown>>) || []).map((item: Record<string, unknown>) => ({ key: crypto.randomUUID(), id: item.id as number, lineNo: item.lineNo as number, masterItemId: item.masterItemId as number|null, description: item.description as string, unit: item.unit as string, rate: item.rate as number, gstPercent: item.gstPercent as number, qty: item.qty as number, netValue: item.netValue as number, quoteMode: (item.quoteMode as string) || "quantity", weightKg: (item.weightKg as number) || null, weightPerUnit: null, pieceCount: (item.pieceCount as number) || null, piecesPerUnit: null }));
  const totals = q.status === "finalized" ? { subTotal: q.subTotal as number, cgst: q.cgst as number, sgst: q.sgst as number, roundOff: q.roundOff as number, netAmount: q.netAmount as number, totalGst: (q.cgst as number)+(q.sgst as number) } : computeTotals(lineItems);
  const header = { customerName: q.customerName as string, customerAddress: (q.customerAddress as string)||"", customerPlace: (q.customerPlace as string)||"", customerGstin: (q.customerGstin as string)||"", quotDate: new Date(q.quotDate as string).toISOString().slice(0,10), refNo: q.refNo as string, deliveryTerms: (q.deliveryTerms as string)||"", gstNote: (q.gstNote as string)||"", validity: q.validity as string, paymentTerms: q.paymentTerms as string };
  return <div className="flex gap-6 h-[calc(100vh-4rem)]"><div className="w-3/5 flex flex-col gap-4 overflow-auto pr-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Link href="/quotations"><Button variant="ghost" size="icon"><ArrowLeft className="h-4 w-4"/></Button></Link><div><h1 className="text-2xl font-bold">Quotation #{q.quotNo as string}</h1><p className="text-sm text-muted-foreground">{q.status as string} · {new Date(q.quotDate as string).toLocaleDateString()}</p></div></div><div className="flex gap-2">{q.status === "draft" && <Link href={`/quotations/${id}/edit`}><Button variant="outline"><Pencil className="h-4 w-4 mr-2"/>Edit</Button></Link>}<Button variant="outline" onClick={duplicate}><Copy className="h-4 w-4 mr-2"/>Duplicate</Button><Button onClick={() => window.open(`/api/quotations/${id}/finalize`, "_blank")}><FileDown className="h-4 w-4 mr-2"/>Download PDF</Button></div></div><Card><CardHeader><CardTitle className="text-base">Customer Details</CardTitle></CardHeader><CardContent><dl className="grid grid-cols-2 gap-2 text-sm"><div><dt className="text-muted-foreground">Name</dt><dd>{header.customerName}</dd></div>{header.customerAddress && <div><dt className="text-muted-foreground">Address</dt><dd>{header.customerAddress}</dd></div>}{header.customerPlace && <div><dt className="text-muted-foreground">Place</dt><dd>{header.customerPlace}</dd></div>}{header.customerGstin && <div><dt className="text-muted-foreground">GSTIN</dt><dd>{header.customerGstin}</dd></div>}</dl></CardContent></Card><Card className="p-4"><h3 className="font-medium mb-3">Line Items</h3><QuotationLineItems lineItems={lineItems} onAdd={()=>{}} onUpdate={()=>{}} onRemove={()=>{}} onMove={()=>{}} readOnly/><div className="mt-4"><QuotationTotals totals={totals}/></div></Card></div><div className="w-2/5 sticky top-0"><h2 className="font-semibold text-sm text-muted-foreground mb-2">Preview</h2><QuotationPreview header={header} lineItems={lineItems} totals={totals}/></div></div>;
}
