"use client"; import { useState, useEffect, useCallback } from "react"; import Link from "next/link";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Eye, Copy } from "lucide-react"; import { toast } from "sonner";
interface QS { id: number; quotNo: string; quotDate: string; customerName: string; status: string; netAmount: number | null; createdBy: { username: string }; }
export default function AdminQuotationsPage() {
  const [quotations, setQuotations] = useState<QS[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState("");
  const fetchQuotations = useCallback(async () => { setLoading(true); const p = new URLSearchParams(); if (search) p.set("search", search); const r = await fetch(`/api/quotations?${p}`); setQuotations(await r.json()); setLoading(false); }, [search]);
  useEffect(() => { fetchQuotations(); }, [fetchQuotations]);
  async function duplicate(id: number) { const r = await fetch(`/api/quotations/${id}/duplicate`, { method:"POST" }); if (r.ok) { toast.success("Duplicated"); fetchQuotations(); } }
  return <div className="space-y-4"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">All Quotations</h1></div><div className="relative max-w-sm"><Input placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)}/></div>
    <div className="border rounded-md"><Table><TableHeader><TableRow><TableHead>Quot No</TableHead><TableHead>Date</TableHead><TableHead>Customer</TableHead><TableHead>Amount</TableHead><TableHead>Created By</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader>
      <TableBody>{loading ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">Loading...</TableCell></TableRow> : quotations.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground">No quotations.</TableCell></TableRow> : quotations.map(q => <TableRow key={q.id}><TableCell className="font-medium">{q.quotNo}</TableCell><TableCell>{new Date(q.quotDate).toLocaleDateString()}</TableCell><TableCell>{q.customerName}</TableCell><TableCell>{q.netAmount != null ? `₹${q.netAmount.toFixed(0)}` : "-"}</TableCell><TableCell>{q.createdBy.username}</TableCell><TableCell><Badge variant={q.status === "finalized" ? "default" : "secondary"}>{q.status}</Badge></TableCell><TableCell><div className="flex gap-1"><Link href={`/quotations/${q.id}`}><Button variant="ghost" size="icon"><Eye className="h-4 w-4"/></Button></Link><Button variant="ghost" size="icon" onClick={() => duplicate(q.id)}><Copy className="h-4 w-4"/></Button></div></TableCell></TableRow>)}</TableBody></Table></div></div>;
}
